### ISSUE TITLE
[plugin:vite:import-analysis]

### ISSUE THREAD

**Issue by ghost** [Zakerxa/Vue-Multi-Image-Upload#2]
Hi I am using vue3 vite typescript in my small project and I tried to use this module but I got messages below

[plugin:vite:import-analysis] Failed to resolve entry for package "@zakerxa/vue-multiple-image-upload". The package may have incorrect main/module/exports specified in its package.json.

Can you help me to resolve this??

**Comment by Zakerxa** [comment]
Actually, I don't use Vite, But I think 
1. You should use the latest version of Vite.
2. Delete your node_modules folder & reinstall back.
3. Please follow this setup [https://www.npmjs.com/package/@zakerxa/vue-multiple-image-upload].
